### ISSUE TITLE
Algemene todo: Refactor doel 2 - vlc naar auk

### ISSUE THREAD

**Issue by Wolfr** [kanselarij-vlaanderen/frontend-kaleidos#732]
In navolging van #705 , is het erna kwestie van  de `.vlc-` componenten te herschrijven naar `.auk-` componenten. Een groot deel hiervan is al gebeurd in het prototype, en daar hebben de componenten reeds een `auk` namespace.

Wat nog niet gebeurd is, is de vergelijking met productie. Dit zal veel makkelijker zijn dan de `vl-`-componenten weg-refactoren, want deze `vlc-` code is nieuwer en de meeste code is initieel door Mono geschreven en is in het algemeen beter gedocumenteerd.

Dit is weer een invidiueel proces van case by case te bekijken hoe we aan de omzetting kunnen werken.

### Heeft wellicht al auk-equivalent

* [x] vlc-box: kan vervangen worden door auk equivalent
* [x] vlc-button: code wellicht niet meer nodig wegens overal consistent gebruik van `auk-button`; ik zie dit nog een paar keer terugkomen in de code #799
* [x] vlc-container #798
* [x] vlc-input
* [x] vlc-key-value
* [x] vlc-hr
* [x] vlc-navbar
* [x] vlc-panel
* [x] vlc-pill
* [x] vlc-tabs-reverse
* [x] vlc-tabs
* [x] vlc-toolbar

### Na te kijken

* [x] vlc-backlink
* [x] vlc-block-link
* [x] vlc-button-in-input
* [x] vlc-button-link
* [x] vlc-button-toolbar
* [x] vlc-date-range
* [ ] vlc-document-card
  * Status: on-hold (`auk-document-card` is corresponderend component)
* [ ] vlc-document-list (gebeurt werk aan: https://github.com/mono-company/kaleidos-prototype-v3/issues/88 )
  * Status: on-hold (`auk-document-list` is corresponderend component)
* [ ] vlc-environment-pill - is de pill die toont in welke dev omgeving je zit, kan vereenvoudigd worden imo
  * Vraag: éénvoudiger qua stijl of qua code?
* [ ] vlc-dropdown-menu
  * Vraag: momenteel geen (volledig uitgewerkt) alternatief voor?
* [x] vlc-input-field-block
* [ ] vlc-list-section-header
  * Status: on-hold (`auk-section-header` is corresponderend component)
* [x] vlc-minister
* [ ] vlc-mock-login #786
  * Status: on-hold (eerst uitzoeken of `ember-mock-login` aan te passen valt)
* [x] vlc-new-session
* [x] vlc-page-header
* [ ] vlc-pagination
  * Status: on-hold (enkel gebruik binnen `number-pagination` component, die enkel binnen mock-login pagina voor komt & daar niet functioneert)
  * Vraag: in zijn geheel verwijderen?
* [x] vlc-panel-layout
* [x] vlc-printable-agenda-list
* [x] vlc-preview-container
* [ ] vlc-procedure-step
  * Status: on-hold (`auk-procedure-step` is corresponderend component)
* [x] vlc-publication-overview
* [x] vlc-publication-status-pill
* [x] vlc-radio-inline
* [ ] vlc-rdfa-editor
  * Status: on-hold
* [x] vlc-scroll-wrapper
* [x] vlc-search
* [x] vlc-search-legend
* [x] vlc-side-nav
* [ ] vlc-status-timeline
  * Status: on-hold
* [ ] vlc-subline
  * Status: on-hold
* [x] vlc-themes-selector
* [ ] vlc-toaster-button
  * Status: on-hold
* [x] vlc-user
* [x] vlc-user-management-table
* [x] vlc-link-actions
* [x] vlc-login
* [x] vlc-color-badge-holder
* [x] vlc-color-badge
* [ ] vlc-decision-result-select
  * Status: on-hold
* [ ] vlc-numac-nummer-list
  * Status: on-hold

### Ondertussen toegevoegd

* [x] vlc-publication-status-selector
* [x] vlc-subcase-description-grid

### Agenda related

Zou ik niet mee beginnen, zie #788

* [ ] vlc-agenda-detail-sidebar
* [ ] vlc-agenda-detail-sidebar-item
* [ ] vlc-agenda-detail-sidebar-section-header
* [ ] vlc-agenda-items-section-header
* [ ] vlc-agenda-items
* [ ] vlc-agenda-meta

**Comment by Wolfr** [comment]
Deze issue is eigenlijk een beetje verkeerd geformuleerd. Ik herschrijf.

**Comment by brenner-company** [comment]
Opmerking mbt refactoring per component zal ik hieronder wat onderhouden.

Box
-----

(geen opmerkingen)


Button
-----

- Aangezien 'button-in-input' hier ook mee overlapte is deze tegelijkertijd mee gerefactored.


Container
-----

- Zoals vermeld binnen #798 zijn een aantal extra sizes toegevoegd binnen de styling van dit component.


Input
-----

(geen opmerkingen)


Key-value
-----

- Hierna moet ook nog even #769 verder opgevolgd worden om alle bestaande (Ember) component instanties terug om te zetten naar HTM/CSS en dit ook aan te passen binnen de styling (mbt toekomstig gebruik).


Hr
-----

- Zou geen slecht idee zijn om hiervoor ook nog even een entry aan te maken binnen de styleguide.


Navbar
-----

(geen opmerkingen)


Panel
-----

(geen opmerkingen)


Pill
-----

(geen opmerkingen)


Tabs + Tabs-reverse
-----

- Aangezien deze 2 versies binnen au-kaleidos-css onder dezelfde noemer gerekend worden, zijn deze tegelijkertijd gerefactored.


Toolbar
-----

- Opgemerkt dat op enkele plaatsen dit component (in pure HTML/CSS vorm) niet correct gebruikt/gestructureerd wordt. Bij het uitvoeren van #802 zal hier extra op gelet moeten worden.


Backlink
-----

(geen opmerkingen)


Block-link
-----

(geen opmerkingen)


Button-in-input
-----

(geen opmerkingen)


Button-link
-----

(geen opmerkingen)


Button-toolbar
-----

(geen opmerkingen)


Date-range
-----

(geen opmerkingen)


Input-field-block
-----

- Door het iets hogere aantal instanties en de mogelijke visuele impact op elementen (binnen en buiten) is hier toch meer tijd in gekropen dan eerst gedacht.


Minister
-----

(geen opmerkingen)


New-session
-----

- Gerefactored met bestaande `auk-` utility/helper classes (enkel `.auk-u-text-condensed-line-height` moeten toevoegen, maar zou die nog eens afgechecked moeten worden of dit, in deze vorm, wel ok is).


Page-header
-----

(geen opmerkingen)


Panel-layout
-----

- Refactor met heel wat impact op omliggende elementen/structuren waardoor nu al een deel van `vlc-side-nav` & `vlc-scroll-wrapper`-refactor hier in mee genomen is.


Printable-agenda-list
-----

- Geen makkelijke refactor aangezien hier de styling ook grotendeels 'broken' was (raar dat hier nooit een issue voor aangemaakt is). Ik heb deze wat in orde gebracht, maar zou effectief nog eens afgetoetst moeten worden aan een design.


Preview-container
-----

(geen opmerkingen)


Publication-overview
-----

- De overblijvende (gerefactored) styling in combinatie met `styles/custom-utilities/_autocomplete.scss` is nog steeds iets raar en lijkt meer op tijdelijke styling dan iets anders. Deze zou op termijn er nog zeker uit moeten gaan.
